AWSTemplateFormatVersion: '2010-09-09'
Description: VPC CloudFormation Template with Parameters

Parameters:
  VpcCidrBlock:
    Type: String
    Description: CIDR block for the VPC
    Default: 10.0.0.0/16
    AllowedPattern: ^(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})\/(\d{1,2})$

Resources:
  MyVPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: !Ref VpcCidrBlock
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: MyVPC

Outputs:
  VpcId:
    Value: !Ref MyVPC
    Description: VPC Id
